language: node_js
node_js: lts/*
#- lts/*
#- v10
#- v9
#- v8
#- v6

install:
- yarn
- npm

script:
- export root=$(pwd)

- mkdir /tmp/yo
- cd /tmp/yo
- yarn global add yo generator-jvm
- echo old-version | yo jvm

- cd ${root}/
- npm i
- npm link
- cd /tmp/yo
- echo new-version | yo jvm

cache:
  yarn: true
  directories:
  - node_modules
