env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8
node_js: lts/*

service:
- docker

addons:
  apt:
    update: true
    packages:
    - libappindicator1
    - fonts-liberation
    - bash
    - curl
    - libxml2-utils
    - docker-ce
    - google-chrome-stable

install: true
before_install:
- nvm install lts/*
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
- sudo add-apt-repository universe -y
- sudo apt-get update -yqq
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends tree jq python-pip
- sudo pip install docker-compose httpie >/dev/null 2>&1

script:
- export base=$(pwd)
- npm i
- npm link
- export e2e=/tmp/yo-e2e-testing
- mkdir -p ${e2e}
- npm i -g yo yeoman-generator
- yo jvm --help

# java-parent-multi-project
- cd ${e2e}
- yo jvm -n javaparentmultiproject -t java-parent-multi-project
- cd javaparentmultiproject/
- cat README.adoc
- cat README.adoc | grep javaparentmultiproject
- ./mvnw -Pdocs
- ./gradlew docum

# kotlin-parent-multi-project
- cd ${e2e}
- yo jvm -n kotlinparentmultiproject -t kotlin-parent-multi-project
- cd kotlinparentmultiproject/
- cat README.adoc
- cat README.adoc | grep kotlinparentmultiproject
- ./mvnw -Pdocs
- ./gradlew docum

# scala-akka-sbt
- cd ${e2e}
- yo jvm -n scala-akka-sbt-project -t scala-akka-sbt
- cd scala-akka-sbt-project/
- ./sbtw clean compile assembly test run
- java -jar target/scala-2.12/*-assembly-*.jar

# replace dots with underscores test
- cd ${e2e}
- yo jvm -n dotted.java1.8 -t java
- cd dotted_java1_8
- ./gradlew -S >/dev/null
- java -jar build/libs/*-all.jar
- bash build/install/dotted_java1_8/bin/dotted_java1_8
- tree build/maven-publish
- ./mvnw clean deploy >/dev/null
- java -jar target/*-all.jar
- tree target/local-repo/

# java
- cd ${e2e}
- yo jvm -n java -t java
- cd java
- ./gradlew -S >/dev/null
- java -jar build/libs/*-all.jar
- bash build/install/java/bin/java
- tree build/maven-publish
- ./gradlew documentation
- ./mvnw clean deploy >/dev/null
- java -jar target/*-all.jar
- tree target/local-repo/
- ./mvnw -P docs >/dev/null

# java-vertx
- cd ${e2e}
- yo jvm -n javavertx -t java-vertx
- cd javavertx
- ./gradlew -S >/dev/null
- ./gradlew documentation >/dev/null
- tree target/generated-docs
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs
- tree target/generated-docs

# kotlin-vertx
- cd ${e2e}
- yo jvm -n kotlinvertx -t kotlin-vertx
- cd kotlinvertx
- ./gradlew -S >/dev/null
- ./gradlew documentation >/dev/null
- tree target/generated-docs
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs
- tree target/generated-docs

# java-ee
- cd ${e2e}
- yo jvm -n javaee -t java-ee
- cd javaee
- ./mvnw >/dev/null
- ./mvnw -Pdocs
- ./gradlew -S >/dev/null
- ./gradlew composeUp
- http :8080/app/api/health
- http :8080/app/api/ping
- http :8080/app/api/pong
- http :8080/app/api/
- ./gradlew composeDown

# java-ee-thymeleaf
- cd ${e2e}
- yo jvm -n javaeeth -t java-ee-thymeleaf
- cd javaeeth
- ./mvnw >/dev/null
- ./mvnw -Pdocs
- ./gradlew -S >/dev/null
- ./gradlew composeUp
- http :8080/app/api/health
- http :8080/app/
- ./gradlew composeDown

# kotlin-ee
- cd ${e2e}
- yo jvm -n kotlinee -t kotlin-ee
- cd kotlinee
- ./mvnw >/dev/null
- ./mvnw -Pdocs
- ./gradlew -S >/dev/null
- ./gradlew composeUp
- http :8080/app/api/health
- http :8080/app/api/
- http :8080/app/api/items value=ololo
- http :8080/app/api/items value=trololo
- http :8080/app/api/items/2
- http :8080/app/api/items
- ./gradlew composeDown

# java-spring-boot
- cd ${e2e}
- yo jvm -n javaspringboot -t java-spring-boot
- cd javaspringboot
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# java-spring-boot-1.x
- cd ${e2e}
- yo jvm -n javaspringboot1x -t java-spring-boot-1.x
- cd javaspringboot1x
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# java-spring-cloud-function-web
- cd ${e2e}/
- yo jvm -n javaspringcloudfunctionweb -t java-spring-cloud-function-web
- cd javaspringcloudfunctionweb
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# kotlin
- cd ${e2e}
- yo jvm -n kotlin -t kotlin
- cd kotlin
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# kotlin-spring-boot
- cd ${e2e}
- yo jvm -n kotlinspringboot -t kotlin-spring-boot
- cd kotlinspringboot
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# kotlin-spring-boot-1.x
- cd ${e2e}
- yo jvm -n kotlinspringboot1x -t kotlin-spring-boot-1.x
- cd kotlinspringboot1x
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# kotlin-spring-cloud-function-web
- cd ${e2e}
- yo jvm -n kotlinspringcloudfunctionweb -t kotlin-spring-cloud-function-web
- cd kotlinspringcloudfunctionweb
- ./gradlew -S >/dev/null
- ./mvnw clean deploy >/dev/null
- ./mvnw -Pdocs

# done
- cd ${base}

deploy:
  provider: npm
  email: daggerok@gmail.com
  api_key:
    secure: DrmOZYpyBV1xTPT5r9mt3+Lcavr/edeRLD3M9nsejaCvtA0bq2i6H5pKOropkCL2A55zl/4ROvgIXKsqSn0neShGUJ2CJBzoWeahgzSMl/A+g7gNAebeFvJgmueq98y5M/4Wxf6C1c+WsyscCdDYj+QdR/IwcuFynpc3sKamKIemqE38/4dUc3LGYvAqLr5BYlgEbnyuk/Y4iHmGDjcGDb5wBmbfURaOj+T4iYJUFddxBBOntP+ddp6pnUrompDdkYOIGrVGrYFqRAVGKW1uYkJoB6ENf5U2BWh3Zs6K0LgELchXiWW6UmOqc8RmFYgwfsV/GhcWxCszgIYBrwIMwoDGNNPU6laMeb4Gx8mhHIZAb1WAOeHyZth5ikzHPGMtCmqPG84INCd/nTrYzGaQvRYMweXXIt7jjstbo5MWZ6Chm8Bu9fTv3otOGw1nFGvqnADuBoUL26xob2fWS5S7oVMoBowNfctG/3Svgpl1bz7V07Hc/8RiSBgArgvxle0D3xu5FzkF7pNYRLFHAKYDvb8n8AMrMmgfs4uu2ggorzrIInelU27Ga3awalwYuei4kgfSmyuut3llDOPOyB24kvnA7VKA444NuQcKQsqkgWPdwpm9g9FmGtl2Y4uyP1rwyENf3Xboi7dB+BnJfxDK1v3taPOGxiypo7/RJOg0fTI=
  all_branches: true
  skip_cleanup: true
  on:
    repo: daggerok/generator-jvm
#  tag: next

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

cache:
  yarn: true
  directories:
  - node_modules
  - .m2
  - .gradle
  - $HOME/.m2
  - $HOME/.sbt
  - $HOME/.gradle
  - $HOME/.docker
