version: '2.2'
services:
  <%= projectDirectory %>-app:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    ports: ['8080:8080']
    networks: [backing-services]
networks:
  backing-services:
    driver: bridge
