version: '2.1'

services:

  gradle-<%= projectDirectory %>-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ['gradle-<%= projectDirectory %>-app-data:/home/appuser']
    ports: ['8080:8080']
    restart: unless-stopped
    # container limit: 200Mb (200 * 1024 * 1024)
    mem_limit: 209715200
    networks:
      public-network:
        aliases:
        - app

volumes:
  gradle-<%= projectDirectory %>-app-data:

networks:
  public-network:
    driver: bridge
