service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - docker-ce
  - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:
- bash ./mvnw >/dev/null
- bash ./gradlew >/dev/null

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
