service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - docker-ce
  - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80

script:
# maven
- bash ./mvnw >/dev/null
- bash ./mvnw -pl ear com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up -P docker >/dev/null
- wait_for 8080
- docker logs -f ear_maven-<%= projectDirectory %>-app_1 &
- sleep 35
- http :8080/web/
- http --form :8080/servlet/api/ name=Max
- http post :8080/rest/api/ name=Maksim
- http :8080/jsp/
- bash ./mvnw -pl ear com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down -P docker >/dev/null 2>&1
- stop_any 8080 80
# gradle
- bash ./gradlew >/dev/null
- bash ./gradlew composeUp >/dev/null
- sleep 3
- wait_for 8080
- docker logs -f ear_gradle-<%= projectDirectory %>-app_1 &
- http :8080/web/
- http --form :8080/servlet/api/ name=Maksim
- http post :8080/rest/api/ name=Maksimko
- http :8080/jsp/
- bash ./gradlew composeDown >/dev/null 2>&1
- stop_any 8080 80
# gradle (maven profile)
- bash ./gradlew -Pprofile=maven clean build composeUp >/dev/null
- wait_for 8080
- docker logs -f ear_maven-<%= projectDirectory %>-app_1 &
- sleep 3
- http :8080/web/
- http --form :8080/servlet/api/ name=Maksimko
- http post :8080/rest/api/ buddy=Max
- http :8080/jsp/
- bash ./gradlew -Pprofile=maven composeDown >/dev/null 2>&1
- stop_any 8080 80

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
