service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - docker-ce
  - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:
- bash gradlew >/dev/null
- bash ./build/install/<%= projectDirectory %>/bin/<%= projectDirectory %> &
- sleep 5
- sudo killall -9 java
#
- bash gradlew clean distZip >/dev/null
- unzip -o ./build/distributions/<%= projectDirectory %>-0.0.1.zip -d /tmp
- bash /tmp/<%= projectDirectory %>-0.0.1/bin/<%= projectDirectory %> &
- sleep 5
- sudo killall -9 java
#
- bash gradlew clean installDist composeUp
- bash gradlew composeDown

cache:
  directories:
  - $HOME/.gradle
