version: "2.1"

services:

  <%= projectDirectory %>:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    volumes: ["<%= projectDirectory %>-data:/home/appuser"]
    networks: [backing-services]
    ports: ["8080:8080"]
    #restart: unless-stopped
    #mem_limit: 838860800 # 800Mb

volumes:
  <%= projectDirectory %>-data: {}

networks:
  backing-services:
    driver: bridge
