service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - docker-ce
  - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80

script:
- bash ./gradlew >/dev/null
- bash ./gradlew composeUp >/dev/null
- http :8080/app/
- http --verify=no https://127.0.0.1:4848/
- bash ./gradlew composeDown >/dev/null 2>&1
# faces maven
- bash ./mvnw >/dev/null 2>&1
- bash ./mvnw clean package com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up -P docker
- sleep 40
- http :8080/app/
- http :9990/console/index.html
- bash ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down -P docker >/dev/null 2>&1

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
